# Generated by Django 4.2 on 2025-02-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_rename_timestamp_message_created_at_and_more'),
    ]

    operations = [
    ]
