# Generated by Django 4.2 on 2025-02-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64, unique=True)),
                ('date_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
    ]
