# Generated by Django 4.2.19 on 2025-02-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_user', '0004_subscription_weatherdata_delete_subscriber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='humidity_unit',
            field=models.CharField(default='%', max_length=10),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='temperature_unit',
            field=models.CharField(default='Celsius', max_length=10),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='wind_speed_unit',
            field=models.CharField(default='m/s', max_length=10),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['latitude', 'longitude'], name='bot_user_su_latitud_c047b8_idx'),
        ),
    ]
